name: Build and run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install gcc13
      run: sudo apt-get install gcc-13 && sudo ln -sf g++-13 /usr/bin/c++
    - name: clone viper
      run: ./install.sh
    - name: make
      run: make
    - name: make tests
      run: make run_tests_md
