name: Build and run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: install gcc13
      run: sudo apt-get install gcc-13 && sudo ln -sf g++-13 /usr/bin/c++
    - name: clone viper
      run: ./install.sh
    - name: make
      run: make
    - name: run tests
      run: ./github_run_tests.sh >> $GITHUB_STEP_SUMMARY
